version: '3'

services:
  maildev:
    container_name: maildev
    image: djfarrelly/maildev
    restart: always
    ports:
      - '25:25'
    environment:
      - VIRTUAL_HOST
networks:
  default:
    external:
      name: nginx-proxy
